[package]
name = "game"
version = "0.1.0"
edition = "2021"
authors = ["Dmitrii Fedorin"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.14.0"
memoffset = "0.6.5"
sdl2 = "0.35.2"
